EXERCISE 5
#+SETUPFILE: group.org
#+OPTIONS: \n:t

* TODO 
 DEADLINE: <2009-11-25 Mer>

* 1. SQL Isolation Levels
** 1. For each of the eight classes, describe a locking protocol that allows only transactions in this class. Does the locking protocol for a given class make any assumptions about the locking protocols used for other classes? Explain briefly.
   
** 2. Consider a schedule generated by the execution of several SQL transactions. Is it guaranteed to be conflict serializable? To be final state serializable? To be recoverable?

** 3. Consider a schedule generated by the execution of several SQL transactions, each of which has READ ONLY access-mode. Is it guaranteed to be conflict serializable? To be final state serializable? To be recoverable?

** 4. Consider a schedule generated by the execution of several SQL transactions, each of which has SERIALIZABLE isolation-level. Is it guaranteed to be conflict serializable? To be final state serializable? To be recoverable?

** 5. For each combination determine whether the following anomalies will occur: inconsistent read, dirty read, lost update, and phantom.

* 2. Crash Recovery
** 1. What is done during Analysis after the first restart? (Be precise about the points at which Analysis begins and ends and describe the contents of any tables constructed in this phase.)

** 2. What is done during Redo after the first restart? (Be precise about the points at which Redo begins and ends.)

** 3. What is done during Undo between the first restart and the second restart? (Be precise about the points at which Undo begins and ends.)

** 4. What is the log at the beginning of the second restart? What is done during Analysis after the second restart?

** 5. What is done during Redo after the second restart?

** 6. What is done during Undo between the second restart and the third restart?

** 7. What is the log at the beginning of the third restart? What is done during Analysis after the third restart?

** 8. What is done during Redo of the third restart?

** 9. What is done during Undo of the third restart?
