EXERCISE 12
#+SETUPFILE: "options.org"


* Exercise 12.1

** 1. (0,1,P), (0,2,P), (2,0,D), (1,0,R), (0,2,A), (0,1,A)

** 2. (0,1,P),(0,2,P),(2,0,R),(1,0,R),(0,2,C),(0,1,C)
In the first phase, we first calculate the permutation of the first 4 messages, so that we have 4! = 4*3*2*1 = 24.
Since it is not possible to have response of a site before sending "prepare" to it. So the order of (0,1,P) and (1,0,R) is fixed. The same applies to site 2. So we get the permutation in the first phase as 4! / (2! * 2!) = 6.
In the second phase we have 2 posible sequenses, which are (0,2,C),(0,1,C) or (0,1,C),(0,2,C).
So we get the total number of possible sequences as 6 * 2 = 12

** 3. If site 1 wants to commit and site 2 does not, we calculate the possible sequences number according to the different position of the "do not commit" message.

First situation, we have a sequence as: (), (), (), (2,0,D), (), (). 
Apply the same method in question 2, we have the permutation: (3! / 2!) * 2! = 6.
Second situation, we have a sequence as : (), (), (2,0,D), (), (), (). Because the coordinator doesn't wait for the response from site 1 any more when it receives "do not commit" from any site. So the order of the last 3 message can be arbitrary. So we get the permutation is 2! * 3! = 12
Third situation, we have a sequence as : (0,2,P), (2,0,D), (0,1,P), (), (), (). We think even if a "do not commit" is received by coordinator before it send other "prepare", it will still send the "prepare". So the order of first 3 messages is fixed in this situation, and the last 3 messages have arbitrary order. Therefore the permutation is 3! = 6.

In a sum, we have the possible sequences number = 6 + 12 + 6 = 24.

** 4. 6

** 5. (2n! * n!)/2^n

* Exercise 12.2

** 1.
// we have it in last year exercise 7.3. please type it in? :P

** 2.

** 3. First we do the projection of r on Y, then ship the projection result to site B.
Then we do natural join of the projection and relation s, then we get a reduction of s with respect to r.
Then we ship the reduction of s to site A, and compute the natural join of the reduction and r.

The total transmition is the size of the tuples of the projection on Y in r, plus the size of the reduction of s with respect to r.
