EXERCISE 7
#+SETUPFILE: options.org

* TODO 
  DEADLINE: <2009-12-09 Mer>

* Exercise 7.1
  Given two relations R(x, y) and S(y, z) and the following data:
  - T(R) = 1000
  - T(S) = 600
  - V(R, Y) = 150
  - V(S, Y) = 40
  - min(R.y) = min(S.y) = 0 and max(R.y) = max(S.y) = 200
  Where V(R, A) is the number of distinct numbers of attribute A in relation R
  Given the following expressions:
  + \sigma_{y=2}(R)
  + \sigma_{y<3}(R)
  + R \Join S
  
** 1. If we assume uniform distribution, what is the selectivity of each of the expressions?
   - \sigma_{y=2}(R):
     F = 1/ICARD(colindex)
     so $F = 1/150$
   - \sigma_{y<3}(R)
     $F(\sigma_{y < 3}(R)) = F(NOT(\sigma_{y >= 3})(R)) = F(NOT(\sigma_{y > 3 or y == 3})(R)) =$
     $1 - ((3 / 200) + (1 / 150)) - (3 / 200)*(1/150) = (29347 / 30000)$
     This number is very close to 1, and in fact this selection is removing only a small part of the data.
   - R \Join S
     $F(R \Join S) = 1 / max(V(R, y), V(S, y)) = 1 / 150$
     

** 2. If the database holds a histogram of the relations as follows, what are the selectivities?
   - \sigma_{y=2}(R):
     Simply the number of tuples where y=2 divided by the total number of tuples.
     $F(\sigma_{y=2}(R)) = 100 / 1000 = 1/10$
   - \sigma_{y<3}(R)
     Counting the tuples where y < 3, so:
     $F(\sigma_{y<3}(R)) = (300 + 120 + 100) / 1000 = 520 / 1000 \approx 1/2$
   - $R \Join S$
     In this case we can only have 10 tuples in our output at maximum.
     Given that in the interval 161-200 we have 600 values and given that in each bucket the distribution is uniform, we can be sure that all those 10 values of y in R will match a value of y in S.
     $F(R \Join S) = 10 / V(R, y) * V(S, y) = 10 / (40 * 150) = 1/600$

** 3. What are the error rates of the first estimation against the second?
   

* Exercise 7.2
  Consider the query $\pi_{A,B,C,D}(R \Join_{A=C} S)$
  - R is 10 pages long
  - R tuples are 300 bytes long
  - S is 100 pages long
  - S tuples are 500 bytes long
  - C is a key for S
  - A is a key for R
  - page size is 1024 bytes
  - combined size of A,B,C,D is 450 bytes

** 1. Cost of writing out the final result

** 2. Suppose that three buffer pages are available, the only join method that is implemented is page-oriented nested loops, and 1/10 of the tuples are removed as duplicates after projection.

*** (a) Compute the cost of doing the projection followed by the join.

*** (b) Compute the cost of doing the join followed by the projection.

*** (c) Compute the cost of doing the join first and then the projection on-the-fly.

*** (d) Would your answers change if 11 buffer pages were available?
